### ISSUE TITLE
ENH use svglib for conversion to various formats

### ISSUE THREAD

**Issue by beckermr** [biggles-plot/biggles#70]
@esheldon I wonder if we can use svglib instead of gs to implement the new write functions? 

See here https://pypi.python.org/pypi/svglib/

This might make the code more portable.

**Comment by esheldon** [comment]
I used gs since I thought it would be installed on every system, and was already used for the pdf writing (converting from eps).  It also dealt nicely with cropping.  Thoughts?

**Comment by beckermr** [comment]
No idea. Command line dependencies like this are tough since they are not in pypi.

**Comment by beckermr** [comment]
I tried this on my machine. The PNGs would not open. :(

**Comment by esheldon** [comment]
which did you try, the svglib or gs?

**Comment by beckermr** [comment]
Ohhh sorry! svglib

**Comment by beckermr** [comment]
Realistically, if we want to develop biggles further we need to add a modern backend.

**Comment by esheldon** [comment]
The only thing the backend is missing, from my point of view as a linux user, is the ability to write anti-aliased images directly rather than going through eps.  Going through eps is slow and requires calling an external program to do the conversion.


If we want to get a larger user base (the motivation for which is to get more code contributors, and thus more features and bug fixes) it needs to be pip installable without the user also installing plotutils separately.

Another thing people like is jupyter notebooks.  In fact many people don't even use x11 windows to show plots any more, they just use jupyter in the browser (I am not one of these).

To get biggles to work in that environment, one would need to have it jupyter aware, and provide the hook needed so that the image gets displayed inline.  Not sure if this is an issue for the backend or not.  I know pyx works in jupyter already, so that is a potential big plus.

**Comment by beckermr** [comment]
Yeah. I agree. With Cairo or pyx, we would easily address all of these concerns. Even matplotlib backends are not totally pip installable.

**Comment by esheldon** [comment]
Note pyx requires a latex installation
